const POSTS=window.HORIONIS_POSTS||[];const COUNTS=window.HORIONIS_COUNTS||{};const FALLBACKS=['assets/astro3.webp','assets/astro.webp','assets/astro2.webp','assets/astro4.webp'];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(s){if(!s)return'';const d=new Date(s.replace(' ','T'));return d.toLocaleDateString('es-AR',{day:'2-digit',month:'short',year:'numeric'})}
function fallbackFor(post,i=0){const c=(post.categories||[]).join(' ').toLowerCase();if(c.includes('ovni'))return'assets/astro4.webp';if(c.includes('historia'))return'assets/astro2.webp';if(c.includes('ciencia'))return'assets/astro3.webp';if(c.includes('misterio'))return'assets/astro.webp';return FALLBACKS[i%FALLBACKS.length]}
function imgFor(post,i=0){return post.thumbnail||fallbackFor(post,i)}function articleUrl(p){return`/${encodeURIComponent(p.slug)}`}
function mountNav(){const nav=document.querySelector('.nav');if(!nav)return;const tick=()=>nav.classList.toggle('scrolled',scrollY>18);tick();addEventListener('scroll',tick,{passive:true});const b=document.querySelector('.menu-btn');if(b)b.onclick=()=>document.querySelector('.nav-links')?.classList.toggle('mobile-open')}
function mountReveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('in'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal:not(.in)').forEach(el=>io.observe(el))}
function mountCursor(){const g=document.querySelector('.cursor-glow');if(!g||matchMedia('(pointer:coarse)').matches)return;addEventListener('pointermove',e=>{g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'},{passive:true})}
function mountStars(){const c=document.getElementById('starfield');if(!c||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const x=c.getContext('2d');let stars=[];function rs(){const r=Math.min(devicePixelRatio,2);c.width=innerWidth*r;c.height=innerHeight*r;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(r,0,0,r,0,0);stars=Array.from({length:Math.min(180,Math.floor(innerWidth/7))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.25+.15,a:Math.random()*.78+.2,v:Math.random()*.1+.02}))}function draw(){x.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){s.y+=s.v;if(s.y>innerHeight)s.y=0;x.beginPath();x.arc(s.x,s.y,s.r,0,Math.PI*2);x.fillStyle=`rgba(210,235,255,${s.a})`;x.fill()}requestAnimationFrame(draw)}rs();draw();addEventListener('resize',rs,{passive:true})}
function mountTilt(){if(matchMedia('(pointer:coarse)').matches)return;document.querySelectorAll('[data-tilt]').forEach(card=>{if(card.dataset.tiltMounted)return;card.dataset.tiltMounted='1';card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*3.5}deg) rotateX(${-y*3.5}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
function firstVideoId(p){const s=p.content||'';let m=s.match(/youtube\.com\/embed\/([\w-]+)/i)||s.match(/youtube\.com\/watch\?v=([\w-]+)/i)||s.match(/youtu\.be\/([\w-]+)/i);return m?m[1]:''}
function normalizeLegacyHtml(content=''){const clean=content.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/\son\w+\s*=\s*(["']).*?\1/gi,'').replace(/javascript:/gi,'').replace(/<!--more-->/gi,'').replace(/\swidth=["']\d+["']/gi,'').replace(/\sheight=["']\d+["']/gi,'');const chunks=clean.split(/\n\s*\n+/).map(s=>s.trim()).filter(Boolean);return chunks.map(ch=>/^<(?:p|div|iframe|img|ul|ol|blockquote|h[1-6]|table|figure|video)\b/i.test(ch)?ch:`<p>${ch.replace(/\n/g,'<br>')}</p>`).join('\n')}
function postCard(p,i=0){return`<article class="post-card reveal"><a href="${articleUrl(p)}"><div class="post-media"><img loading="lazy" src="${esc(imgFor(p,i))}" onerror="this.onerror=null;this.src='${fallbackFor(p,i)}'" alt=""></div><div class="post-body"><div class="post-meta"><span>${esc((p.categories||[])[0]||'Archivo')}</span><span>${fmtDate(p.date)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.excerpt||'Exploración del archivo Horionis.')}</p><span class="readmore">Abrir expediente →</span></div></a></article>`}
function footerYear(){const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear()}
function initCommon(){mountNav();mountReveal();mountCursor();mountStars();mountTilt();footerYear()}document.addEventListener('DOMContentLoaded',initCommon);